on:
  push:
    paths: ["input.txt", "summarize.py"]
  pull_request:
    paths: ["input.txt", "summarize.py"]

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Python 셋업
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: LLM 요약 스크립트 실행
        run: |
          python summarize.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: 아티팩트 업로드
        uses: actions/upload-artifact@v4  # ✅ 최신 버전 사용
        with:
          name: llm-summary
          path: summary.txt
