on:
  push:
    paths: ["input.txt", "sum.py"]
  pull_request:
    paths: ["input.txt", "sum.py"]

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Python 셋업
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 의존성 설치
  	run: |
    	   python -m pip install --upgrade pip
           pip install --upgrade openai>=1.2.0

      - name: LLM 요약 스크립트 실행
        run: |
          python sum.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: 아티팩트 업로드
        uses: actions/upload-artifact@v4
        with:
          name:
